nimblehq/infrastructure-templates

- src/templates/aws/advanced.ts
N/A
The type of `rds_autoscaling_max_capacity` was missing.
N/A
The generated template should not have typo issues
> Add missing type in RDS module

- skeleton/aws/main.tf
- skeleton/aws/providers.tf
- src/templates/aws/advanced.ts
Resolves https://github.com/nimblehq/infrastructure-templates/issues/62
- Add versions for terraform and providers
- Move `terraform` and `provider` blocks into `providers.tf` file
N/A
N/A
> [#62] Lock the AWS provider version and Terraform version

- skeleton/aws/modules/rds/variables.tf
- Close #81 
Update the default aurora DB engine to 14.3
Following the latest version from [this page](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.VersionPolicy.html#Aurora.VersionPolicy.MajorVersionLifetime).
Tested in the ewa payroll project:
> [#81] Update the Aurora Postgres engine version from 13 to 14 

- .github/dependabot.yml
Resolves https://github.com/nimblehq/infrastructure-templates/issues/89
- Change the interval to `monthly` to reduce spam PRs
- Limit the open PRs to 3
- Change versioning-strategy to `increase-if-necessary`
Check [this docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#about-the-dependabotyml-file) for more information
N/A
> [#89] Update dependabot configuration

- skeleton/aws/modules/alb/main.tf
- skeleton/aws/modules/alb/variables.tf
- skeleton/aws/modules/bastion/variables.tf
- skeleton/aws/modules/vpc/variables.tf
- src/templates/aws/addons/alb.ts
- Close #111 
- Add `enable_alb_stickiness` and `alb_stickiness_type` for enabling ALB sticky sessions
- Run `terraform fmt` to indent code
N/A
N/A
> [#111] Update the load balancer to support sticky sessions

- skeleton/aws/modules/bastion/variables.tf
- skeleton/aws/modules/ecs/main.tf
- skeleton/aws/modules/vpc/variables.tf
- Close #119
✅ Fetch the most recent task definition from AWS and choose the latest task definition version for deployment
Previously terraform would use the task definition version from its saved state. 
This did NOT account for incrementing task definitions on AWS from outside sources, (e.g CI deployments)
- Example usage of implementation from https://registry.terraform.io/providers/aaronfeng/aws/latest/docs/data-sources/ecs_task_definition#example-usage
Fix is used on Wo*** and applying the latest version from AWS or terraform state
> [#119] Use latest task definition from either AWS or terraform state

- .github/workflows/test.yml
- package.json
- skeleton/aws/modules/alb/main.tf
- skeleton/aws/modules/alb/variables.tf
- skeleton/aws/modules/bastion/variables.tf
- skeleton/aws/modules/vpc/variables.tf
- src/templates/aws/addons/alb.ts
- Close #113
Fix `test` script
- Run Jest with `--watch` option might cause this issue.
- You just need to check https://github.com/nimblehq/infrastructure-templates/pull/122/commits/d65d0ff8e15f201ba574cb2de008023708fe24e9. The current branch has the code from chaining branch as I merged it 😢 
Tested on my local machine
> [#113] Fix: Jest tests are failing but CI still passed

- skeleton/aws/README.md
- skeleton/aws/modules/ecs/main.tf
- skeleton/aws/modules/ecs/service.json.tftpl
- skeleton/aws/modules/ecs/variables.tf
- skeleton/aws/modules/ssm/main.tf
- skeleton/aws/modules/ssm/outputs.tf
- skeleton/aws/modules/ssm/variables.tf
- src/templates/aws/addons/ecs.ts
- src/templates/aws/addons/ssm.ts
- Close #104 
- Refactor how to add environment variables to ECS Task. Now we just need to update the list of environment variables in a variable.
- Refactor the SSM module to reduce work when adding a new secret variable. Now we just need to create a new variable in the main `variables.tf` file, then add it to the secrets object in the SSM module.
- Reference from EWA project.
- Still keep using SSM instead of Secret manager as we don't need to rotate the secret right now.
N/A
> [#104] Improve the way to manage environment variables and secrets

- src/templates/aws/addons/ssm.ts
- Close #148
- Fix the wrong `database_url` in SSM module
As we're using the [Template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) to declare the multiple-line string, then we need to escape the `${}` by using `/${}`, but when writing it to the file, the `/` was not removed. That is why it's incorrect.
The generated code is correct:
**Before:**
**After:**
> [#148] Fix: Wrong database_url string in SSM module

- src/templates/aws/addons/alb.ts
- src/templates/aws/addons/bastion.ts
- src/templates/aws/addons/cloudwatch.ts
- src/templates/aws/addons/ecr.ts
- src/templates/aws/addons/ecs.ts
- src/templates/aws/addons/rds.ts
- src/templates/aws/addons/s3.ts
- src/templates/aws/addons/securityGroup.ts
- src/templates/aws/addons/ssm.ts
- src/templates/aws/addons/vpc.ts
- Close #179
If we generate a project on the current `develop` branch, the generated projects cannot be initialized because of wrong paths to the modules. 
It happens because we changed the project structure in previous PRs.
The newly generated project now contains the correct paths to the modules.
Shared folder:
> Initializing modules...
> - ecr in ../modules/ecr
Base folder:
> Initializing modules...
> - alb in ../modules/alb
> - bastion in ../modules/bastion
> - cloudwatch in ../modules/cloudwatch
> - ecs in ../modules/ecs
> - rds in ../modules/rds
> Downloading registry.terraform.io/terraform-aws-modules/rds-aurora/aws 6.2.0 for rds.db...
> - rds.db in .terraform/modules/rds.db
> - s3 in ../modules/s3
> - security_group in ../modules/security_group
> - ssm in ../modules/ssm
> - vpc in …
> [#179] Fix: generated project can't be run

- .github/workflows/lint.yml
- skeleton/addons/versionControl/github/.github/workflows/lint.yml
- Close #176
- The `cancel-workflow-action` has been removed from both the template workflow and the generated project workflow.
- The `concurrency` attribute has been used in workflows to guarantee that only one job runs for each workflow.
- A discussion on Slack raised the need to move away from using the `cancel-workflow-action`: https://nimble-co.slack.com/archives/CSQG2QXFX/p1679635544024489
- The official documentation for using workflows can be found here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
- Similar implementations can also be found on the Rails templates: https://github.com/nimblehq/rails-templates/pull/398 
- and Compas: https://github.com/nimblehq/compass/pull/1228 repositories.
CI should pass 🤞 
Previous PR was …
> [#176] Replace cancel-workflow-action with GH concurrency

- .gitignore
- skeleton/addons/versionControl/github/.github/workflows/lint.yml
- skeleton/aws/modules/alb/main.tf
- skeleton/aws/modules/bastion/main.tf
- skeleton/aws/modules/cloudwatch/main.tf
- skeleton/aws/modules/ecr/main.tf
- skeleton/aws/modules/ecs/main.tf
- skeleton/aws/modules/s3/main.tf
- skeleton/aws/modules/vpc/main.tf
- skeleton/core/.tool-versions
- src/templates/aws/addons/alb.ts
- src/templates/aws/addons/bastion.ts
- src/templates/aws/addons/ecs.ts
- src/templates/aws/addons/rds.ts
- Close #155
- Add the `tfsec` GH action into the generated project template. `TFSEC_VERSION` specified with the required `v` prefix, as `tfsec` uses this format for [release tags](https://github.com/aquasecurity/tfsec/tags).
- Also `tfsec` is included in the `.tool-versions` file for asdf, so that developers can run checks locally during the development process.
Our template had multiple warnings listed by tfsec. A few of these warnings were addressed and resolved accordingly, while others were silenced since they don't have much sense.
CI for newly generated project:
> [#155] Add tfsec to the CI of the generated project

- skeleton/aws/modules/ecs/main.tf
- skeleton/aws/modules/ecs/variables.tf
- skeleton/aws/modules/iam_group_membership/main.tf
- skeleton/aws/modules/iam_group_membership/variables.tf
- skeleton/aws/modules/iam_groups/data.tf
- skeleton/aws/modules/iam_groups/main.tf
- skeleton/aws/modules/iam_groups/outputs.tf
- skeleton/aws/modules/iam_users/main.tf
- skeleton/aws/modules/iam_users/outputs.tf
- skeleton/aws/modules/iam_users/variables.tf
- src/templates/aws/addons/core/iamUserAndGroup.test.ts
- src/templates/aws/addons/core/iamUserAndGroup.ts
- src/templates/aws/addons/index.ts
- src/templates/aws/index.ts
- Close #160 
This PR allows the provisioning of IAM groups & users by code.
- This PR follows the [implementation](https://github.com/easyhoteluk/aws-infrastructure/pull/107) in a recent project (easyHotel) with some modifications.
- Simplify the custom IAM policy, there is only one policy taken from https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_aws_my-sec-creds-self-manage.html
- The user is prevented from doing any actions until they have MFA set.
- Due to the above reason, the user is not forced to set a password on the first login.
> This policy **does not allow users to reset a password while signing in** to the AWS Management Console for the first time. We recommend that you do not grant permissions to new users until after they sign in. You can allow …
> [#160] Creating the IAM groups & users

- skeleton/aws/README.md
- Close #196
- Add the documentation in the starter kit for the AWS addon.
- Extra: Lint markdown and fix some typos.
`n/a`
> [#196] Document the ALB Target Group Health Check configuration

- templates/addons/aws/modules/iam_groups/main.tf
- Close #207
- Actually, this is not a fix. We ignore it because we intend to do it
The policy that cause this error was copied from [this guide](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_aws_my-sec-creds-self-manage.html)
|Before|After|
|------|------|
|![image](https://github.com/nimblehq/infrastructure-templates/assets/7344405/99ebd0f8-e9e9-46f2-9245-fa2770c91d31)|![image](https://github.com/nimblehq/infrastructure-templates/assets/7344405/94b16524-fe8b-49ba-88db-f16d6391a134)|
> [#207] Fix: The tfsec fails due to aws-iam-no-policy-wildcards rule

- .github/wiki/Getting-Started.md
- package-lock.json
- src/commands/generate/index.test.ts
- src/commands/generate/index.ts
- src/commands/install/index.test.ts
- src/generators/addons/terraformCloud/index.test.ts
- src/generators/addons/terraformCloud/index.ts
- src/generators/addons/versionControl/index.test.ts
- src/generators/addons/versionControl/index.ts
- templates/terraform/core/main.tf
- templates/terraform/shared/main.tf
- test/matchers/file.ts
- test/matchers/index.d.ts
- Close #191
- Add Terraform Cloud add-on
- Refactor Version Control add-on and make it isolated
- Remove `cloud` block in skeleton files
- Fix tests to work with the new add-ons
- We implemented the VersionControl prompt in the `generate` command file, but it will make the versionControl depends on that command. We need to make it isolated so that we can call it in anywhere
- In each add-on, I use the value `terraformCloudEnabled` instead of `enabled` because with this, we can test them easier by passing all values in a single mock object.
- Tests are passed
- The prompt is shown when creating a new project:
> [#191] Add prompt to enable Terraform Cloud

- .gitignore
- package-lock.json
- package.json
- tsconfig.json
- Close #215
- Add [`ttypescript`](https://github.com/cevek/ttypescript) and [`typescript-transform-paths`](https://github.com/LeDDGroup/typescript-transform-paths) to compile TS path aliases to relative paths
- [This SO answer](https://stackoverflow.com/a/63432939) helped
- As we still use TS 4, so we still use [`ttypescript`](https://github.com/cevek/ttypescript) instead of [`ts-patch`](https://github.com/nonara/ts-patch) which works with TS 5+
`npm publish` runs without errors (except the authentication)
|Before|After|
|---|---|
|![image](https://github.com/nimblehq/infrastructure-templates/assets/7344405/cf6f872d-3ea9-486d-9d19-7818c2e3aa5b)|![image](https://github.com/nimblehq/infrastructure-templates/assets/7344405/822d9060-26db-4be2-8385-01e09aa80411)|
> [#215] Fix: The template can not be published

- .github/wiki/Getting-Started.md
- bin/run
- package-lock.json
- package.json
- src/generators/addons/terraformCloud/index.ts
- src/helpers/terraform.test.ts
- src/helpers/terraform.ts
- src/hooks/postProcess.ts
- Close #219
- Fix Cannot use 'import.meta' outside a module
- Beautify the error message when `terraform not found`, it should not display the error details:
This was a bug when upgrading the OCLIF library, as we were using the ES module syntax in the code. You can check the #219 content to get more details.
Try publishing and it works:
`npx @nimblehq/infra-template@2.0.2-beta.4 generate demo-project`
> [#219] Fix: Cannot use 'import.meta' outside a module

- .gitignore
- templates/terraform/gitignore
- no ticket ref
It's a good idea to include IDE files in gitignore, as most developers will likely use these IDEs.
Tests are green.
> [Chore] Add IDE files to .gitignore

- .github/release-drafter.yml
- .github/workflows/draft-new-release.yml
- Close #145
- Use https://github.com/release-drafter/release-drafter to draft a new release after merged to main
- The config is copied from https://github.com/nimblehq/android-templates/blob/develop/.github/release-drafter-config.yml
N/A
Workflow run: https://github.com/nimblehq/infrastructure-templates/actions/runs/6609598250
Drafted release: https://github.com/nimblehq/infrastructure-templates/releases/tag/untagged-b1ea34b6ada36c0166d9
> [#145] Add a workflow to draft a new release

- package.json
- Bump version to 2.2.0
- The previous PR was merged to wrong branch
N/A
On the Files changed tab
> [Chore] Bump version to 2.2.0

- package-lock.json
- templates/addons/aws/modules/iam_groups/data.tf
- templates/addons/aws/modules/iam_groups/main.tf
- Close #246
Fix syntax for IAM access policy.
The fix based on this PR: https://github.com/Jollibee-Foods-Corporation/smashburger-infrastructure-aws/pull/5 (you need JFC repo access for it).
Before the fix TF plan stage was passed, but on apply stage we had an error:
After the fix the plan can be applied correctly:
> [#246] Fix: Wrong syntax for the policy document of full_iam_access_policy

- src/generators/addons/aws/modules/core/iamUserAndGroup.ts
- templates/addons/aws/modules/iam_groups/data.tf
- templates/addons/aws/modules/iam_groups/main.tf
- templates/addons/aws/modules/iam_groups/outputs.tf
- Close #254
List of implemented improvements:
- Disable console login for service account (`has_login = false`). It is unnecessary for service account to have console login and exposes more risk. Credentials that will be used by service account can be generated through admin account.
- Rename `bot` to `infra-service-account`, since this name is more accurate describe why we need this account
- Set `depends_on` attribute to `group_membership`. Without `depends_on` there was an error when we tried to add new user, it said that user wasn't created yet.
- Refactor `group_membership` to be set through forloop, to make it easier change attributes (otherwise we had to set same `depends_on` for all three memberships).
TF plan can be run and applied without any errors:
> [#254] Prevent creating the login credential for IAM bot account
